const AG_GRID_LOCALE_ES = {
    // Set Filter
    selectAll: '(Seleccionar todo)',
    selectAllSearchResults: '(Seleccionar todos los resultados de búsqueda)',
    searchOoo: 'Buscar...',
    blanks: '(En blanco)',
    noMatches: 'No hay coincidencias',

    // Number Filter & Text Filter
    filterOoo: 'Filtrar...',
    equals: 'Igual',
    notEqual: 'No igual',
    blank: 'En blanco',
    notBlank: 'No en blanco',
    empty: 'Seleccionar uno',

    // Number Filter
    lessThan: 'Menos que',
    greaterThan: 'Mayor que',
    lessThanOrEqual: 'Menos o igual que',
    greaterThanOrEqual: 'Mayor o igual que',
    inRange: 'En rango',
    inRangeStart: 'desde',
    inRangeEnd: 'hasta',

    // Text Filter
    contains: 'Contiene',
    notContains: 'No contiene',
    startsWith: 'Comienza con',
    endsWith: 'Termina con',

    // Date Filter
    dateFormatOoo: 'yyyy-mm-dd',

    // Filter Conditions
    andCondition: 'Y',
    orCondition: 'O',

    // Filter Buttons
    applyFilter: 'Aplicar',
    resetFilter: 'Reiniciar',
    clearFilter: 'Limpiar',
    cancelFilter: 'Cancelar',

    // Filter Titles
    textFilter: 'Filtro de texto',
    numberFilter: 'Filtro numérico',
    dateFilter: 'Filtro de fecha',
    setFilter: 'Establecer filtro',

    // Group Column Filter
    groupFilterSelect: 'Seleccionar campo:',

    // Advanced Filter
    advancedFilterContains: 'contiene',
    advancedFilterNotContains: 'no contiene',
    advancedFilterTextEquals: 'es igual a',
    advancedFilterTextNotEqual: 'no es igual a',
    advancedFilterStartsWith: 'comienza con',
    advancedFilterEndsWith: 'termina con',
    advancedFilterBlank: 'está en blanco',
    advancedFilterNotBlank: 'no está en blanco',
    advancedFilterEquals: '=',
    advancedFilterNotEqual: '!=',
    advancedFilterGreaterThan: '>',
    advancedFilterGreaterThanOrEqual: '>=',
    advancedFilterLessThan: '<',
    advancedFilterLessThanOrEqual: '<=',
    advancedFilterTrue: 'es verdadero',
    advancedFilterFalse: 'es falso',
    advancedFilterAnd: 'Y',
    advancedFilterOr: 'O',
    advancedFilterApply: 'Aplicar',
    advancedFilterValidationMissingColumn: 'Falta la columna',
    advancedFilterValidationMissingOption: 'Falta la opción',
    advancedFilterValidationMissingValue: 'Falta el valor',
    advancedFilterValidationInvalidColumn: 'Columna no encontrada',
    advancedFilterValidationInvalidOption: 'Opción no encontrada',
    advancedFilterValidationMissingQuote: 'Falta una comilla final',
    advancedFilterValidationNotANumber: 'El valor no es un número',
    advancedFilterValidationMissingCondition: 'Falta la condición',
    advancedFilterValidationJoinOperatorMismatch: 'Los operadores de unión dentro de una condición deben ser iguales',
    advancedFilterValidationInvalidJoinOperator: 'Operador de unión no encontrado',
    advancedFilterValidationMissingEndBracket: 'Falta un corchete final',
    advancedFilterValidationExtraEndBracket: 'Demasiados corchetes finales',
    advancedFilterValidationMessage: 'La expresión tiene un error. ${variable1} - ${variable2}.',
    advancedFilterValidationMessageAtEnd: 'La expresión tiene un error. ${variable} al final de la expresión.',

    // Side Bar
    columns: 'Columnas',
    filters: 'Filtros',

    // columns tool panel
    pivotMode: 'Modo de pivote',
    groups: 'Agrupar filas',
    rowGroupColumnsEmptyMessage: 'Arrastra aquí para establecer filas de agrupación',
    values: 'Valores',
    valueColumnsEmptyMessage: 'Arrastra aquí para agregar',
    pivots: 'Etiquetas de columna',
    pivotColumnsEmptyMessage: 'Arrastra aquí para establecer etiquetas de columna',

    // Header of the Default Group Column
    group: 'Grupo',

    // Row Drag
    rowDragRow: 'fila',
    rowDragRows:'filas',

    // Other
    loadingOoo: 'Cargando...',
    loadingError: 'ERR',
    noRowsToShow: 'No hay filas para mostrar',
    enabled: 'Habilitado',

    // Menu
    pinColumn: 'Fijar columna',
    pinLeft: 'Fijar a la izquierda',
    pinRight: 'Fijar a la derecha',
    noPin: 'Sin fijar',
    valueAggregation: 'Agregación de valores',
    noAggregation: 'Ninguna',
    autosizeThiscolumn: 'Ajustar automáticamente esta columna',
    autosizeAllColumns: 'Ajustar automáticamente todas las columnas',
    groupBy: 'Agrupar por',
    ungroupBy: 'Desagrupar por',
    ungroupAll: 'Desagrupar todo',
    addToValues: 'Agregar ${variable} a los valores',
    removeFromValues: 'Quitar ${variable} de los valores',
    addToLabels: 'Agregar ${variable} a las etiquetas',
    removeFromLabels: 'Quitar ${variable} de las etiquetas',
    resetColumns: 'Restablecer columnas',
    expandAll: 'Expandir todos los grupos de filas',
    collapseAll: 'Cerrar todos los grupos de filas',
    copy: 'Copiar',
    ctrlC: 'Ctrl+C',
    ctrlX: 'Ctrl+X',
    copyWithHeaders: 'Copiar con encabezados',
    copyWithGroupHeaders: 'Copiar con encabezados de grupo',
    cut: 'Cortar',
    paste: 'Pegar',
    ctrlV: 'Ctrl+V',
    export: 'Exportar',
    csvExport: 'Exportar a CSV',
    excelExport: 'Exportar a Excel',

    // Enterprise Menu Aggregation and Status Bar
    sum: 'Suma',
    first: 'Primero',
    last: 'Último',
    min: 'Mínimo',
    max: 'Máximo',
    none: 'Ninguno',
    count: 'Conteo',
    avg: 'Promedio',
    filteredRows: 'Filtrado',
    selectedRows: 'Seleccionado',
    totalRows: 'Total de filas',
    totalAndFilteredRows: 'Filas',
    more: 'Más',
    to: 'a',
    of: 'de',
    page: 'Página',
    pageLastRowUnknown: '?',
    nextPage: 'Siguiente página',
    lastPage: 'Última página',
    firstPage: 'Primera página',
    previousPage: 'Página anterior',

    // Pivoting
    pivotColumnGroupTotals: 'Total',

    // Enterprise Menu (Charts)
    pivotChartAndPivotMode: 'Gráfico pivotante y Modo pivotante',
    pivotChart: 'Gráfico pivotante',
    chartRange: 'Rango del gráfico',

    columnChart: 'Gráfico de columnas',
    groupedColumn: 'Agrupado',
    stackedColumn: 'Apilado',
    normalizedColumn: 'Columna 100% apilada',

    barChart: 'Gráfico de barras',
    groupedBar: 'Agrupado',
    stackedBar: 'Apilado',
    normalizedBar: 'Barra 100% apilada',

    pieChart: 'Gráfico circular',
    pie: 'Circular',
    doughnut: 'Dona',

    line: 'Línea',

    xyChart: 'Gráfico XY (Dispersión)',
    scatter: 'Dispersión',
    bubble: 'Burbuja',

    areaChart: 'Gráfico de áreas',
    area: 'Área',
    stackedArea: 'Área apilada',
    normalizedArea: 'Área 100% apilada',

    histogramChart: 'Gráfico de histograma',
    histogramFrequency: "Frecuencia",

    combinationChart: 'Gráfico de combinación',
    columnLineCombo: 'Columna y línea',
    AreaColumnCombo: 'Área y columna',

    // Charts
    pivotChartTitle: 'Gráfico pivotante',
    rangeChartTitle: 'Gráfico de rango',
    settings: 'Configuración',
    data: 'Datos',
    format: 'Formato',
    categories: 'Categorías',
    defaultCategory: '(Ninguna)',
    series: 'Series',
    xyValues: 'Valores XY',
    paired: 'Modo emparejado',
    axis: 'Eje',
    navigator: 'Navegador',
    color: 'Color',
    thickness: 'Grosor',
    xType: 'Tipo de X',
    automatic: 'Automático',
    category: 'Categoría',
    number: 'Número',
    time: 'Tiempo',
    autoRotate: 'Rotación automática',
    xRotation: 'Rotación X',
    yRotation: 'Rotación Y',
    ticks: 'Marcas',
    width: 'Ancho',
    height: 'Altura',
    length: 'Longitud',
    padding: 'Relleno',
    spacing: 'Espaciado',
    chart: 'Gráfico',
    title: 'Título',
    titlePlaceholder: 'Título del gráfico - Haz doble clic para editar',
    background: 'Fondo',
    font: 'Fuente',
    top: 'Arriba',
    right: 'Derecha',
    bottom: 'Abajo',
    left: 'Izquierda',
    labels: 'Etiquetas',
    size: 'Tamaño',
    minSize: 'Tamaño mínimo',
    maxSize: 'Tamaño máximo',
    legend: 'Leyenda',
    position: 'Posición',
    markerSize: 'Tamaño del marcador',
    markerStroke: 'Trazo del marcador',
    markerPadding: 'Relleno del marcador',
    itemSpacing: 'Espaciado del elemento',
    itemPaddingX: 'Relleno X del elemento',
    itemPaddingY: 'Relleno Y del elemento',
    layoutHorizontalSpacing: 'Espaciado horizontal',
    layoutVerticalSpacing: 'Espaciado vertical',
    strokeWidth: 'Ancho de trazo',
    lineDash: 'Guiones de línea',
    offset: 'Desplazamiento',
    offsets: 'Desplazamientos',
    tooltips: 'Descripciones emergentes',
    callout: 'Llamada',
    markers: 'Marcadores',
    shadow: 'Sombra',
    blur: 'Desenfoque',
    xOffset: 'Desplazamiento X',
    yOffset: 'Desplazamiento Y',
    lineWidth: 'Ancho de línea',
    normal: 'Normal',
    bold: 'Negrita',
    italic: 'Cursiva',
    boldItalic: 'Negrita cursiva',
    predefined: 'Predefinido',
    fillOpacity: 'Opacidad de relleno',
    strokeOpacity: 'Opacidad de trazo',
    histogramBinCount: 'Recuento de intervalos',
    columnGroup: 'Columna',
    barGroup: 'Barra',
    pieGroup: 'Circular',
    lineGroup: 'Línea',
    scatterGroup: 'XY (Dispersión)',
    areaGroup: 'Área',
    histogramGroup: 'Histograma',
    combinationGroup: 'Combinación',
    groupedColumnTooltip: 'Agrupado',
    stackedColumnTooltip: 'Apilado',
    normalizedColumnTooltip: 'Columna 100% apilada',
    groupedBarTooltip: 'Agrupado',
    stackedBarTooltip: 'Apilado',
    normalizedBarTooltip: 'Barra 100% apilada',
    pieTooltip: 'Circular',
    doughnutTooltip: 'Dona',
    lineTooltip: 'Línea',
    groupedAreaTooltip: 'Área',
    stackedAreaTooltip: 'Área apilada',
    normalizedAreaTooltip: 'Área 100% apilada',
    scatterTooltip: 'Dispersión',
    bubbleTooltip: 'Burbuja',
    histogramTooltip: 'Histograma',
    columnLineComboTooltip: 'Columna y línea',
    areaColumnComboTooltip: 'Área y columna',
    customComboTooltip: 'Combinación personalizada',
    noDataToChart: 'No hay datos disponibles para representar en un gráfico.',
    pivotChartRequiresPivotMode: 'El gráfico pivotante requiere el modo pivotante habilitado.',
    chartSettingsToolbarTooltip: 'Menú',
    chartLinkToolbarTooltip: 'Vinculado a la cuadrícula',
    chartUnlinkToolbarTooltip: 'Desvinculado de la cuadrícula',
    chartDownloadToolbarTooltip: 'Descargar gráfico',
    seriesChartType: 'Tipo de gráfico de series',
    seriesType: 'Tipo de serie',
    secondaryAxis: 'Eje secundario',

    // ARIA
    ariaAdvancedFilterInput: 'Entrada de filtro avanzado',
    ariaChecked: 'seleccionado',
    ariaColumn: 'Columna',
    ariaColumnGroup: 'Grupo de columnas',
    ariaColumnList: 'Lista de columnas',
    ariaColumnSelectAll: 'Alternar selección de todas las columnas',
    ariaDateFilterInput: 'Entrada de filtro de fecha',
    ariaDefaultListName: 'Lista',
    ariaFilterColumnsInput: 'Entrada de filtro de columnas',
    ariaFilterFromValue: 'Filtrar desde el valor',
    ariaFilterInput: 'Entrada de filtro',
    ariaFilterList: 'Lista de filtro',
    ariaFilterToValue: 'Filtrar hasta el valor',
    ariaFilterValue: 'Valor del filtro',
    ariaFilterMenuOpen: 'Abrir menú de filtro',
    ariaFilteringOperator: 'Operador de filtrado',
    ariaHidden: 'oculto',
    ariaIndeterminate:'indeterminado',
    ariaInputEditor: 'Editor de entrada',
    ariaMenuColumn: 'Presiona CTRL ENTER para abrir el menú de columnas.',
    ariaRowDeselect: 'Presiona ESPACIO para deseleccionar esta fila',
    ariaRowSelectAll: 'Presiona ESPACIO para alternar la selección de todas las filas',
    ariaRowToggleSelection: 'Presiona ESPACIO para alternar la selección de la fila',
    ariaRowSelect: 'Presiona ESPACIO para seleccionar esta fila',
    ariaSearch: 'Buscar',
    ariaSortableColumn: 'Presiona ENTER para ordenar',
    ariaToggleVisibility: 'Presiona ESPACIO para alternar la visibilidad',
    ariaToggleCellValue: 'Presiona ESPACIO para alternar el valor de la celda',
    ariaUnchecked: 'no seleccionado',
    ariaVisible: 'visible',
    ariaSearchFilterValues: 'Buscar valores de filtro',

    // ARIA Labels for Drop Zones

    ariaRowGroupDropZonePanelLabel: 'Grupos de filas',
    ariaValuesDropZonePanelLabel: 'Valores',
    ariaPivotDropZonePanelLabel: 'Etiquetas de columna',
    ariaDropZoneColumnComponentDescription: 'Presiona SUPRIMIR para eliminar',
    ariaDropZoneColumnValueItemDescription: 'Presiona ENTER para cambiar el tipo de agregación',
    ariaDropZoneColumnGroupItemDescription: 'Presiona ENTER para ordenar',
    // used for aggregate drop zone, format: {aggregation}{ariaDropZoneColumnComponentAggFuncSeparator}{column name}
    ariaDropZoneColumnComponentAggFuncSeparator: ' de ',
    ariaDropZoneColumnComponentSortAscending: 'ascendente',
    ariaDropZoneColumnComponentSortDescending: 'descendente',

    // ARIA Labels for Dialogs
    ariaLabelColumnMenu: 'Menú de columnas',
    ariaLabelCellEditor: 'Editor de celdas',
    ariaLabelDialog: 'Diálogo',
    ariaLabelSelectField: 'Seleccionar campo',
    ariaLabelRichSelectField: 'Seleccionar campo enriquecido',
    ariaLabelTooltip: 'Información sobre herramientas',
    ariaLabelContextMenu: 'Menú contextual',
    ariaLabelSubMenu: 'Submenú',
    ariaLabelAggregationFunction: 'Función de agregación',
    ariaLabelAdvancedFilterAutocomplete: 'Autocompletar de filtro avanzado',

    // Number Format (Status Bar, Pagination Panel)
    thousandSeparator: ',',
    decimalSeparator: '.',

    // Data types
    true: 'Verdadero',
    false: 'Falso',
    invalidDate: 'Fecha no válida',
    invalidNumber: 'Número no válido',
    january: 'Enero',
    february: 'Febrero',
    march: 'Marzo',
    april: 'Abril',
    may: 'Mayo',
    june: 'Junio',
    july: 'Julio',
    august: 'Agosto',
    september: 'Septiembre',
    october: 'Octubre',
    november: 'Noviembre',
    december: 'Diciembre',
};

export default AG_GRID_LOCALE_ES;
